done
hmrc/api-hub-applications pull request #12
Opened 2023-02-06 12:50 UTC by tigdik

2023-02-06 14:10 UTC, PaulCDurham requested changes

2023-02-06 14:10 UTC, PaulCDurham commented on test/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepositorySpec.scala
> +
Please add more integration tests covering scenarios like application does not exist, application with existing scopes, adding scopes for all environments.

2023-02-06 14:10 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +
We need to set the application's lastUpdated timestamp. This code uses "pre-prod" as an environment name rather than "preProd". It must use "preProd".

2023-02-06 14:10 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +  def addScopes(applicationId:String, newScopes: Seq[NewScope]) = {
Type annotation required for public member

2023-02-06 14:10 UTC, PaulCDurham commented on test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala
> +
Please remove commented out code

2023-02-07 14:01 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +                  Some(false)
Please can you help me understand what this if statement functionality is for?

2023-02-07 14:05 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +                  Some(false)
I can't find a test scenario that tests Some(false) so I'm not sure in what circumstance it can occur?

2023-02-07 14:05 UTC, laurahk commented on test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala
> +        when(fixture.repository.addScopes(id,scopes)).thenReturn(Future.successful(Some(true) ))
Maybe extract Some(true) into a variable with a meaningful name

2023-02-07 14:08 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +             val envScopes: Seq[(EnvironmentName, String)] = newScopes.foldLeft(Seq[(EnvironmentName,String)]())((m, sc) => m++sc.environments.map(env => (env,sc.name)))
`Seq.empty[(EnvironmentName,String)]` might be clearer than `Seq[(EnvironmentName,String)]()`

2023-02-07 14:09 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +             val envScopes: Seq[(EnvironmentName, String)] = newScopes.foldLeft(Seq[(EnvironmentName,String)]())((m, sc) => m++sc.environments.map(env => (env,sc.name)))
Please name 'm' and 'sc'

2023-02-07 14:12 UTC, tigdik commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +                  Some(false)
Some(false) is for Application not found and hence not documents were updated

2023-02-07 14:17 UTC, laurahk commented on it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala
> +      Some(true) mustBe expected
duplicate assertion here `Some(true) mustBe expected`

2023-02-07 14:20 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +                  Some(false)
ah thank you :) I'd suggest extracting `Some(true)` and `Some(false)` into variables to name them to make it clearer.

2023-02-07 14:21 UTC, laurahk submitted a review, later dismissed

2023-02-07 14:21 UTC, tigdik commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +             val envScopes: Seq[(EnvironmentName, String)] = newScopes.foldLeft(Seq[(EnvironmentName,String)]())((m, sc) => m++sc.environments.map(env => (env,sc.name)))
how can I rename m to sc here: (m, sc)?

2023-02-07 15:45 UTC, tigdik commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +                  Some(false)
I have removed Some(...) completetely

2023-02-07 15:46 UTC, tigdik commented on test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala
> +        when(fixture.repository.addScopes(id,scopes)).thenReturn(Future.successful(Some(true) ))
removed those completetely

2023-02-08 09:16 UTC, laurahk approved these changes

2023-02-08 10:02 UTC, laurahk approved these changes

2023-02-08 10:05 UTC, merged