HIP-1159: Handle deployment failure response
hmrc/api-hub-applications pull request #124
Opened 2024-05-07 15:52 UTC by llmikeyj

2024-05-07 16:05 UTC, llmikeyj commented
Note: According to my Intellij anyway, there is an error in the simple-api-deployment.yaml where the schema for errors is defined.
I've implement what I believe is the intention rather than follow the rendered example:

![image](https://github.com/hmrc/api-hub-applications/assets/10079986/20d00269-09ef-43e2-af88-d28b884f0f1e)

2024-05-08 09:58 UTC, PaulCDurham requested changes

2024-05-08 09:58 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentError.scala
> +case class DeploymentError(`type`: String, message: String)
Could we call this Error to match the spec?

2024-05-08 09:58 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentFailure.scala
> +case class DeploymentFailure(code: String, reason: String, errors: Option[Seq[DeploymentError]])
Could we call this FailuresResponse to match the spec?

2024-05-08 10:02 UTC, edgarjimenez commented
> Note: According to my Intellij anyway, there is an error in the simple-api-deployment.yaml where the schema for errors is defined. I've implement what I believe is the intention rather than follow the rendered example:
> 
> ![image](https://private-user-images.githubusercontent.com/10079986/328595113-20d00269-09ef-43e2-af88-d28b884f0f1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjI1MDMsIm5iZiI6MTcxNTE2MjIwMywicGF0aCI6Ii8xMDA3OTk4Ni8zMjg1OTUxMTMtMjBkMDAyNjktMDllZi00M2UyLWFmODgtZDI4Yjg4NGYwZjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZDg1YjViYTc2NDEzMjM0YjM2YTYzYTE2YTkwZjExYTA4OThlMWY4NjU3YmMxZGMzNGMyYjA0ZjMwZmIyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oH5UWVGrDTdmyds66g0dylVp4KDtVCGBfrtMDeOg6Gc)

@llmikeyj are you sure you are referencing the latest OAS version? v0.6.0 looks different to what is shown on your image

2024-05-08 10:05 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentError.scala
> +case class DeploymentError(`type`: String, message: String)
I chose DeploymentError to differentiate this from any other Error types, and because this structure is only used by the deployment APIs

2024-05-08 10:07 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentFailure.scala
> +case class DeploymentFailure(code: String, reason: String, errors: Option[Seq[DeploymentError]])
Yes, but same comments as above

2024-05-08 11:12 UTC, PaulCDurham approved these changes

2024-05-08 11:22 UTC, merged