HIPP-1293: Domain and subdomain on generate
hmrc/api-hub-applications pull request #136
Opened 2024-06-05 11:29 UTC by llmikeyj

2024-06-06 09:04 UTC, PaulCDurham requested changes
I don't think we should do that validation in the backend - see below. Happy to discuss as that's just an opinion.

2024-06-06 09:04 UTC, PaulCDurham commented on test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala
> +    "must return 400 Bad Request when subdomain is present but domain is not" in {
As per above, I don't think we should do this.

2024-06-06 09:04 UTC, PaulCDurham commented on test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala
> +          None
We're using None everywhere. Could we use Some(stuff) in maybe just the first positive test at least?

2024-06-06 12:13 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/controllers/DeploymentsController.scala
> +        case JsSuccess(deploymentsRequest, _) if deploymentsRequest.subdomain.isDefined && deploymentsRequest.domain.isEmpty =>
ok

2024-06-06 12:13 UTC, llmikeyj commented on test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala
> +          None
ok

2024-06-06 12:13 UTC, llmikeyj commented on test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala
> +    "must return 400 Bad Request when subdomain is present but domain is not" in {
ok

2024-06-07 10:20 UTC, PaulCDurham approved these changes

2024-06-07 10:20 UTC, merged