HIPP-364: Add service layer in api-hub-applications
hmrc/api-hub-applications pull request #17
Opened 2023-02-17 15:04 UTC by PaulCDurham

https://jira.tools.tax.service.gov.uk/browse/HIPP-364

2023-02-17 17:50 UTC, llmikeyj reviewed
LGTM.

2023-02-17 17:51 UTC, llmikeyj approved these changes

2023-02-20 09:36 UTC, llmikeyj approved these changes
LGTM.

2023-02-23 14:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala
>            applications.filter(_.hasProdPendingScope)
I think it would be better if the filtering was in a service layer method. Perhaps add a pendingScopes method to the service layer?

2023-02-23 14:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala
> +    def addScope(environment: EnvironmentName, scopeName: String): Application =
This isn't used anywhere

2023-02-23 14:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
>  import org.mongodb.scala.model.Updates.{addEachToSet, combine, set}
Unused import

2023-02-23 14:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +import org.mongodb.scala.bson.conversions.Bson
Unused import

2023-02-23 14:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +    val withLastUpdated = application.copy(lastUpdated = LocalDateTime.now())
The idea was to set lastUpdated in the service layer so we can test it accurately using the injected clock.

2023-02-23 14:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +            case "dev" =>
There is no business case for setting scope status in environments other than production. The only valid changes are PENDING to APPROVED at the moment.

2023-02-23 14:43 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +                Some(application.setProdScopes(application.environments.prod.scopes.map(scope => if (scope.name == scopeName) scope.copy(status = updateStatus.status) else scope)))
We should only ever update an existing scope with a status of PENDING. This code could update any scope by name. What about if a scope was requested, denied, and then requested again? We'd get two APPROVED.

2023-02-23 14:44 UTC, PaulCDurham commented on it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala
> -    }
We remove this test?

2023-02-23 14:47 UTC, PaulCDurham commented on it/uk/gov/hmrc/apihubapplications/ApplicationsServiceIntegrationSpec.scala
> +class ApplicationsServiceIntegrationSpec extends AnyFreeSpec
I don't think we need an integration test specifically for this class. It should be unit tested against a mock repository. The existing integration tests should be sufficient to make sure the layers work together.

2023-02-23 15:42 UTC, laurahk commented
Quite a few unused imports. Just run `sbt clean test` to see:

```
[warn] /Users/hmrc/Documents/projects/api-hub-applications/app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala:26:52: Unused import
[warn] import uk.gov.hmrc.apihubapplications.repositories.ApplicationsRepository
[warn]                                                    ^
[warn] /Users/hmrc/Documents/projects/api-hub-applications/app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala:21:43: Unused import
[warn] import org.mongodb.scala.bson.conversions.Bson
[warn]                                           ^
[warn] /Users/hmrc/Documents/projects/api-hub-applications/app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala:22:41: Unused import
[warn] import org.mongodb.scala.model.Updates.{addEachToSet, combine, set}
[warn]                                         ^
[warn] /Users/hmrc/Documents/projects/api-hub-applications/app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala:22:55: Unused import
[warn] import org.mongodb.scala.model.Updates.{addEachToSet, combine, set}
[warn]                                                       ^
[warn] /Users/hmrc/Documents/projects/api-hub-applications/app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala:22:64: Unused import
[warn] import org.mongodb.scala.model.Updates.{addEachToSet, combine, set}
[warn]                                                                ^
[warn] /Users/hmrc/Documents/projects/api-hub-applications/app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala:26:26: Unused import
[warn] import java.time.{Clock, LocalDateTime}
[warn]                          ^
[warn] 6 warnings found
[info] compiling 4 Scala sources to /Users/hmrc/Documents/projects/api-hub-applications/target/scala-2.13/test-classes ...
[warn] /Users/hmrc/Documents/projects/api-hub-applications/test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala:40:52: Unused import
[warn] import uk.gov.hmrc.apihubapplications.repositories.ApplicationsRepository
[warn]                                                    ^
[warn] /Users/hmrc/Documents/projects/api-hub-applications/test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala:22:22: Unused import
[warn] import play.api.libs.json
[warn]                      ^
[warn] /Users/hmrc/Documents/projects/api-hub-applications/test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala:23:27: Unused import
[warn] import play.api.libs.json.Json
[warn]                           ^
[warn] /Users/hmrc/Documents/projects/api-hub-applications/test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala:25:74: Unused import
[warn] import uk.gov.hmrc.apihubapplications.models.application.EnvironmentName._
[warn]
```

2023-02-23 15:46 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala
> +        case JsSuccess(updateStatus, _) =>
Right now we only want to update scopes to a status of APPROVED so I'm not sure why this has been removed?

2023-02-23 15:47 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +            case "dev" =>
Yeah I wouldn't generalise setting the scope status until we need to and the requirements/ACs in tickets require us to do so.

2023-02-23 15:51 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +                Some(application.setProdScopes(application.environments.prod.scopes.map(scope => if (scope.name == scopeName) scope.copy(status = updateStatus.status) else scope)))
This behaviour wasn't defined in the original ticket that implement scope approval i.e. we never checked the status was PENDING before we set it to APPROVED. It's a sensible thing to do for the moment but would require unit/integration tests and a e.g. a 400 return code. Since this is a refactor ticket I would avoid introducing new behaviour as we would want ACs around it.

2023-02-23 15:53 UTC, laurahk commented
A good change to make to the codebase 👍 Just need to address the comments and avoid changing/introducing new behaviour.

2023-02-23 18:57 UTC, tigdik commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +            case "dev" =>
Why then in requirements the json specifies status and URL params specify environment name if there's no other option rather than "prod" and "APPROVED"? Check the task hipp-265

2023-02-23 19:00 UTC, tigdik commented on app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala
> +        case JsSuccess(updateStatus, _) =>
same as above - if the only options are env="prod" and status="APPROVED" why parameters env(URL) and status(json)?

2023-02-24 09:07 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +            case "dev" =>
The endpoint includes the environment for consistency (and incase in the future we want to approve scopes in other environments). Perhaps for this piece of code, just change it to handle `case "prod"` and return an error response for other environments? 

The JSON specifies the status because in the (nearish) future we will be setting status to DENIED as well as approved. We discussed having endpoints specifically for /applications/{id}/environments/{environment}/scopes/{scope-name}/**approve** and /applications/{id}/environments/{environment}/scopes/{scope-name}/**deny** but in the meeting we agreed to keep in generic incase we ever wanted to change the use cases.

So we will have to update this code in the future, just not yet.

2023-02-25 22:00 UTC, tigdik commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +                Some(application.setProdScopes(application.environments.prod.scopes.map(scope => if (scope.name == scopeName) scope.copy(status = updateStatus.status) else scope)))
I have replaced this method with setPendingProdScopeStatusToApproved(...)

2023-02-25 22:02 UTC, tigdik commented on it/uk/gov/hmrc/apihubapplications/ApplicationsServiceIntegrationSpec.scala
> +class ApplicationsServiceIntegrationSpec extends AnyFreeSpec
deleted

2023-02-27 14:55 UTC, laurahk commented on app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala
> +    def addScopes(environment: EnvironmentName, scopes: Seq[String]): Application =
this should have a test in ApplicationLensesSpec

2023-02-27 15:08 UTC, laurahk commented on it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala
> +        response.status shouldBe 404
For my own notes: my first thought here was, "should this be a 400 or 404"? But I guess it's 404 because we can't find the scope in a PENDING state. So it's fine as is 👍

2023-02-27 15:09 UTC, laurahk commented on it/resources/application.conf
> +}
nice addition! 😄

2023-02-27 15:12 UTC, laurahk requested changes
Just the Application Lenses test to write. Everything else looks great. I've checked out the code and tested it using Postman. I'm just going to add the AC about approving a scope that is already approved as an AC so we have a record of the behaviour.

2023-02-28 11:06 UTC, tigdik commented on it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala
> +        response.status shouldBe 404
check A/C of HIPP-251. I think it is correct as this test is about adding scopes to invalid environment, e.g. "env-does-not-exist"

2023-02-28 11:43 UTC, laurahk commented on it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala
> +        response.status shouldBe 404
This test does not have an invalid environment - it is trying to change the scope on prod of a scope that is already approved. Either way - it's fine, it was just a note for myself so feel free to resolve this conversation.

2023-02-28 11:46 UTC, laurahk approved these changes

2023-02-28 14:01 UTC, merged