HIPP-1615: Refactor to handle APIM deployment responses failures
hmrc/api-hub-applications pull request #192
Opened 2024-10-23 15:14 UTC by victorarbuesmallada

APIM outages would prevent our users to see deployment statuses. Instead of propagating the outage errors, we are just returning different deployment status types.

2024-10-25 10:50 UTC, PaulCDurham requested changes

2024-10-25 10:50 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/controllers/DeploymentsController.scala
> +        )
What happens to the Left result? Everywhere else we have a `case Left(e) => throw e` that handles that explicitly. Does Play know what to do with the Left?

2024-10-28 12:36 UTC, victorarbuesmallada commented on app/uk/gov/hmrc/apihubapplications/controllers/DeploymentsController.scala
> +        )
At this point, I thought we were returning just a sequence of deployment statuses and the left result is handled on the service, which turns that into an `Unexpected` deployment status

2024-10-28 12:42 UTC, victorarbuesmallada commented on app/uk/gov/hmrc/apihubapplications/connectors/APIMConnectorImpl.scala
> +      }
the [http client](https://github.com/hmrc/http-verbs/blob/2710cda3e057ab5c99c6d9210399d1364f503bad/http-verbs-play-30/src/main/scala/uk/gov/hmrc/http/client/HttpClientV2Impl.scala#L309-L312) that we use makes the future fail in timeout/gateway issues, that's why I needed the `recover` block.

2024-10-29 15:42 UTC, PaulCDurham requested changes
Can you check if it's used (I don't think it is) and remove getDeployment from DeploymentsService?

2024-10-29 15:42 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/DeploymentsService.scala
> +      ).value
Why has getDeployment changed? In fact I don't think we need it. This was used by the controller but has been replaced by getDeployments. I'd just delete it.

2024-10-29 17:13 UTC, PaulCDurham approved these changes

2024-10-29 17:28 UTC, merged