Hipp 198
hmrc/api-hub-applications pull request #4
Opened 2023-01-13 09:22 UTC by tigdik

2023-01-13 12:10 UTC, PaulCDurham requested changes
All cool except for a test description.

2023-01-13 12:10 UTC, PaulCDurham commented on test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala
> +    "must return 201 Created for a valid request" in {
Could you add the correct test description? This looks like copy and paste from above. Something like "must return 200 Ok and a JSON array of applications".

2023-01-13 12:22 UTC, PaulCDurham approved these changes

2023-01-16 09:11 UTC, PaulCDurham approved these changes

2023-01-16 10:26 UTC, closed without merging

2023-01-16 10:27 UTC, tigdik commented
closed due to gpg key signing. Other PR will be created based on branch HIPP-198.1 signed with gpg key