HIPP-280: Update README
hmrc/api-hub-applications pull request #61
Opened 2023-06-21 09:57 UTC by PaulCDurham

https://jira.tools.tax.service.gov.uk/browse/HIPP-280

2023-06-21 12:02 UTC, laurahk commented on README.md
> +### IDMS
Please can you say somewhere that secondary connects to IDMS-proxy running in QA where primary connects straight to IDMS.

2023-06-21 12:02 UTC, laurahk requested changes
Please mention IDMS proxy

2023-06-22 08:05 UTC, PaulCDurham commented on README.md
> +### IDMS
Done, although I think bigger explanations of cross-component connectivity should really be documented in Confluence.

2023-06-22 08:45 UTC, laurahk approved these changes

2023-06-22 08:48 UTC, merged