Hipp 839 add credential
hmrc/api-hub-applications pull request #83
Opened 2023-10-31 14:50 UTC by llmikeyj

2023-10-31 15:49 UTC, PaulCDurham requested changes

2023-10-31 15:49 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala
> +        case Right(credential) => Ok(Json.toJson(credential))
If I'm being pedantic, Created rather than Ok?

2023-10-31 15:49 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala
> +    def setPrimaryMasterCredentialSecretFragment(secret: Secret) = {
Not used?

2023-10-31 15:49 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +    if (credentials.isEmpty) {
Do we care, thinking about it? There are no credentials and we don't expect that. But adding a credential lets the user fix it. This would help if the initial IDMS call to create the hidden credential on application registration failed. The user could then "fix" the application and keep using it.

2023-10-31 15:49 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +    if (credentials.isEmpty) {
Again, I'm not sure we care

2023-10-31 15:49 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +      case Right(secret) => Right(application.addPrimaryCredential(masterCredential.setSecretFragment(secret.secret).copy(created = LocalDateTime.now(clock))))
I think we need to set the secret as well as the fragment. We have to return that for its once only viewing.

2023-10-31 15:49 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +      .process(application, Seq(ApplicationEnrichers.credentialCreatingApplicationEnricher(environmentName, application, idmsConnector, clock)))
I don't think this sets the primary secret, just the fragment.

2023-10-31 15:49 UTC, PaulCDurham commented on it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala
> +            case JsSuccess(credential, _) => credential.secretFragment;
Is there an actual assertion here?

2023-10-31 15:49 UTC, PaulCDurham commented on test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
> +  }
Tests look fine except I think we should be returning the secret as well as fragment.

2023-10-31 15:49 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala
> +
Could do with a unit test

2023-10-31 16:41 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +    if (credentials.isEmpty) {
I don't know. Can we leave this here for now and then open up for discussion? Happy path is still covered; unhappy path is undefined

2023-10-31 16:42 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +    if (credentials.isEmpty) {
as above

2023-10-31 16:44 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +      .process(application, Seq(ApplicationEnrichers.credentialCreatingApplicationEnricher(environmentName, application, idmsConnector, clock)))
Not sure what do to about this, sorry

2023-10-31 17:00 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +      .process(application, Seq(ApplicationEnrichers.credentialCreatingApplicationEnricher(environmentName, application, idmsConnector, clock)))
Is the correct thing being stored if we persist this? I don't know any more.

2023-11-01 15:07 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +    if (credentials.isEmpty) {
I've changed this to allow adding a credential when the application for some unknown reason does not already have one.

2023-11-01 15:32 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +      case Right(secret) => Right(application.addPrimaryCredential(masterCredential.setSecretFragment(secret.secret).copy(created = LocalDateTime.now(clock))))
We are now returning the secret

2023-11-01 15:32 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
> +      .process(application, Seq(ApplicationEnrichers.credentialCreatingApplicationEnricher(environmentName, application, idmsConnector, clock)))
The secret is now returned but not stored in Mongo

2023-11-01 16:24 UTC, PaulCDurham commented on test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
> +  }
The tests now assert that a secret is returned as well as the fragment

2023-11-01 16:26 UTC, PaulCDurham commented on it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala
> +            case JsSuccess(credential, _) => credential.secretFragment;
Mike added an assertion so I'll resolve this

2023-11-02 09:06 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala
> +
Merged this enricher into the scope adding one and added an extra test

2023-11-03 11:49 UTC, edgarjimenez approved these changes

2023-11-03 12:03 UTC, PaulCDurham approved these changes

2023-11-03 12:04 UTC, merged