Hipp 915 delete an application
hmrc/api-hub-applications pull request #91
Opened 2023-12-12 12:55 UTC by llmikeyj

2023-12-13 13:00 UTC, PaulCDurham requested changes

2023-12-13 14:39 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/models/application/Application.scala
> +  deletedBy: Option[String]
I did originally have that pattern but had some issues, so I decided to keep consistent with created.

2023-12-13 14:41 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/services/AccessRequestsService.scala
> +                           applicationsService: ApplicationsService )(implicit hc: HeaderCarrier): Future[Either[ApplicationsException, Unit]] = {
That's not really the issue I think. It's more of cross-concerns; the access requests service needing to update applications and vice versa. Really we need a new service composing both for the cross concerns .

2023-12-13 15:11 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +      IndexModel(Indexes.ascending("deleted"))
Removing the index breaks the search.

2023-12-13 15:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala
> +      IndexModel(Indexes.ascending("deleted"))
I would suggest we filter the deleted records out in Scala then. We don't want to use an index that returns 99% of the data. That's highly inefficient.

2023-12-13 15:42 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/AccessRequestsService.scala
> +                           applicationsService: ApplicationsService )(implicit hc: HeaderCarrier): Future[Either[ApplicationsException, Unit]] = {
You could merge them. I split them as ApplicationsService (and its spec) was getting too big. But we're about to delete lots of it when we clean up the MVP code.

2023-12-15 12:20 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/services/AccessRequestsService.scala
> +                           applicationsService: ApplicationsService )(implicit hc: HeaderCarrier): Future[Either[ApplicationsException, Unit]] = {
If we think there is much work in this I vote just leave it as is and let's add a ticket to refactor the services, possibly while doing the remove MVP code work. I don't see thy this ticket should effectively tidy up a load of tech debt.

2023-12-18 09:42 UTC, PaulCDurham requested changes

2023-12-18 09:42 UTC, PaulCDurham commented on app/uk/gov/hmrc/apihubapplications/models/application/Deleted.scala
> +                   deletedBy: TeamMember)
I'm slightly concerned about the future-proofness of this. We introduced TeamMember rather than use a simple string for email address as we thought we might extend TeamMember with other attributes such as "role in the team". Deletion isn't concerned with that so maybe a simple string would be better?

2023-12-18 10:51 UTC, llmikeyj commented on app/uk/gov/hmrc/apihubapplications/models/application/Deleted.scala
> +                   deletedBy: TeamMember)
ok

2023-12-18 11:00 UTC, PaulCDurham approved these changes

2023-12-18 11:00 UTC, merged