Hipp 905 notify team members rejected access
hmrc/api-hub-applications pull request #95
Opened 2024-01-09 10:15 UTC by llmikeyj

2024-01-09 14:49 UTC, edgarjimenez requested changes

2024-01-09 14:49 UTC, edgarjimenez commented on it/uk/gov/hmrc/apihubapplications/EmailConnectorSpec.scala
> +        "microservice.services.email.accessApprovedEmailToTeamTemplateId" -> accessApprovedEmailToTeamTemplateId,
just being picky, but could you keep the access template Ids together?

2024-01-09 15:41 UTC, llmikeyj commented on it/uk/gov/hmrc/apihubapplications/EmailConnectorSpec.scala
> +        "microservice.services.email.accessApprovedEmailToTeamTemplateId" -> accessApprovedEmailToTeamTemplateId,
ok

2024-01-10 09:35 UTC, edgarjimenez approved these changes

2024-01-10 09:43 UTC, merged